//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Product = new HashSet<Product>();
            this.User = new HashSet<User>();
        }
    
        public int OrderID { get; set; }
        public string FullName { get; set; }
        public int IDOrderStatus { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int IDOrderPickupPoint { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickupPoints PickupPoints { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
